export const mockData = {
  trips: [
    {
      id: "1",
      title: "箱根1泊2日 家族で温泉満喫コース",
      author: "サトシ",
      targetAges: "幅広い年齢",
      area: "箱根",
      imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=1000",
      spots: [
        {
          id: "m1",
          type: "transit",
          time: "08:30 - 10:00",
          name: "ロマンスカーで移動",
          icon: "train",
          positive: "展望席の最前列が取れた！子供大興奮。",
          alert: "ベビーカーは折りたたんで指定の荷物置き場へ。事前に乗車位置を確認しておくとスムーズです。",
        },
        {
          id: "s1",
          type: "spot",
          time: "10:00 - 12:00",
          name: "箱根彫刻の森美術館",
          positive: "広い芝生で走り回れる！最高！",
          alert: null,
        },
        {
          id: "m2",
          type: "transit",
          time: "12:00 - 12:30",
          name: "箱根登山鉄道で移動",
          icon: "train",
          positive: null,
          alert: "混雑時はベビーカーを畳む必要あり。抱っこ紐もあると安心。",
        },
        {
          id: "s2",
          type: "spot",
          time: "12:30 - 13:30",
          name: "レストラン○○",
          positive: "子供用椅子あり、辛くないメニューあり",
          alert: "お昼時は1時間待ち！",
        },
        {
          id: "s3",
          type: "spot",
          time: "15:00",
          name: "ホテル△△",
          positive: "ファミリールーム最高！",
          alert: null,
        },
      ],
    },
    {
      id: "2",
      title: "沖縄3泊4日 海遊びと美ら海水族館",
      author: "ユミ",
      targetAges: "未就学児〜小学生",
      area: "沖縄",
      imageUrl: "https://images.unsplash.com/photo-1540151812223-c30b3fab58e6?auto=format&fit=crop&q=80&w=1000",
      spots: [
        {
          id: "m3",
          type: "transit",
          time: "07:00 - 09:30",
          name: "飛行機（羽田発）",
          icon: "plane",
          positive: "後ろの席を取ると、気兼ねなくシートを倒せたり、トイレに立ちやすくて正解でした！",
          alert: "耳抜き用の飲み物やお菓子は手荷物のすぐ出せる位置に必須。",
        },
        {
          id: "s4",
          type: "spot",
          time: "10:00 - 14:00",
          name: "美ら海水族館",
          positive: "ジンベエザメに大興奮！",
          alert: "館内はベビーカーだと移動しづらい場所あり",
        },
      ],
    },
  ],
};